[package]
name = "js-abi"
version = "0.1.0"
edition = "2024"

[dependencies]
query_system_info = { path = ".." }
napi        = "3.0.0"
napi-derive = "3.0.0"

[build-dependencies]
napi-build = "2"

[lib]
name = "js_abi"
path = "src/lib.rs"
crate-type = ["cdylib"]
